import { useEffect, useMemo, useState } from 'react'
import { PlusCircle, Trash2 } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import PageHeader from '../components/PageHeader'
import { db } from '../db/database'
import { uid } from '../lib'
import type { ReadyWorkoutModality, ReadyWorkoutTemplate } from '../types'
const labels:Record<ReadyWorkoutModality,string>={resistance:'Resistido',functional:'Funcional',cross_training:'Cross Training',hiit:'HIIT',hybrid:'Híbrido'}
export default function ReadyWorkoutsPage(){const nav=useNavigate(),[list,setList]=useState<ReadyWorkoutTemplate[]>([]),[duration,setDuration]=useState<'all'|'30'|'45'|'60'>('all'),[modality,setModality]=useState<'all'|ReadyWorkoutModality>('all');const load=async()=>setList((await db.readyWorkouts.toArray()).filter(x=>x.workoutTemplate?.blocks).sort((a,b)=>a.name.localeCompare(b.name)));useEffect(()=>{void load()},[]);const filtered=useMemo(()=>list.filter(x=>(duration==='all'||x.durationMinutes===+duration)&&(modality==='all'||x.modality===modality)),[list,duration,modality]);async function add(x:ReadyWorkoutTemplate){const t=structuredClone(x.workoutTemplate);t.name=x.name;t.createdAt=new Date().toISOString();t.updatedAt=t.createdAt;t.blocks=t.blocks.map((b,i)=>({...b,id:uid(),order:i,exercises:b.exercises.map((e,j)=>({...e,id:uid(),order:j}))}));await db.workouts.add(t);alert('Treino adicionado a Meus Treinos.')}return <div className="page"><PageHeader title="Treinos Prontos" subtitle="Biblioteca separada de modelos"/><button className="secondary" onClick={()=>nav('/treinos')}>← Voltar</button><section className="card"><div className="field-grid two"><label>Duração<select value={duration} onChange={e=>setDuration(e.target.value as typeof duration)}><option value="all">Todas</option><option value="30">30 min</option><option value="45">45 min</option><option value="60">60 min</option></select></label><label>Modalidade<select value={modality} onChange={e=>setModality(e.target.value as typeof modality)}><option value="all">Todas</option>{Object.entries(labels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label></div></section><div className="stack">{filtered.map(x=><article className="card" key={x.id}><div className="section-title-row"><div><h3>{x.name}</h3><small>{labels[x.modality]} • {x.durationMinutes} min • {x.source==='system'?'Modelo LIFTY':'Meu modelo'}</small></div>{x.source==='personal'&&<button className="icon-btn danger" onClick={async()=>{if(confirm('Excluir este modelo pessoal?')){await db.readyWorkouts.delete(x.id!);await load()}}}><Trash2 size={17}/></button>}</div><div className="chip-row">{x.workoutTemplate.blocks.map(b=><span className="chip" key={b.id}>{b.name}</span>)}</div><button className="primary full" onClick={()=>add(x)}><PlusCircle size={18}/>Adicionar à minha rotina</button></article>)}{!filtered.length&&<div className="card empty">Nenhum modelo para este filtro.</div>}</div></div>}
