import { useEffect, useState } from 'react'
import { BookOpen, ClipboardPaste, Copy, Pencil, Plus, Share2, Sparkles, Trash2, X } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import PageHeader from '../components/PageHeader'
import { db } from '../db/database'
import { importLiftyText, uid, workoutToLiftyText } from '../lib'
import type { BlockModel, ReadyWorkoutModality, WorkoutTemplate } from '../types'
const now=()=>new Date().toISOString();const labels:Record<BlockModel,string>={resistance:'Resistido',cardio:'Cardio',interval:'Intervalado'}
export default function WorkoutsPage(){const nav=useNavigate();const[list,setList]=useState<WorkoutTemplate[]>([]);const[showTextImport,setShowTextImport]=useState(false);const[sharedText,setSharedText]=useState('');const load=async()=>setList((await db.workouts.toArray()).filter(w=>!w.archived).sort((a,b)=>a.name.localeCompare(b.name)));useEffect(()=>{void load()},[])
 async function duplicate(w:WorkoutTemplate){const x=structuredClone(w);delete x.id;x.name+=' - cópia';x.createdAt=now();x.updatedAt=x.createdAt;x.blocks=x.blocks.map((b,i)=>({...b,id:uid(),order:i,exercises:b.exercises.map((e,j)=>({...e,id:uid(),order:j}))}));await db.workouts.add(x);await load()}
 async function saveReady(w:WorkoutTemplate){const duration=Number(prompt('Duração: 30, 45 ou 60 minutos','45'));if(![30,45,60].includes(duration))return;const modality=(prompt('Modalidade: resistance, functional, cross_training, hiit ou hybrid','hybrid')||'hybrid') as ReadyWorkoutModality;if(!['resistance','functional','cross_training','hiit','hybrid'].includes(modality))return alert('Modalidade inválida.');const copy=structuredClone(w);delete copy.id;await db.readyWorkouts.add({name:w.name,modality,durationMinutes:duration as 30|45|60,source:'personal',workoutTemplate:copy,createdAt:now(),updatedAt:now()});alert('Salvo em Treinos Prontos pessoais.')}
 async function copyText(text:string){try{await navigator.clipboard.writeText(text);return true}catch{const a=document.createElement('textarea');a.value=text;a.style.position='fixed';a.style.opacity='0';document.body.appendChild(a);a.select();const ok=document.execCommand('copy');a.remove();return ok}}
 async function shareWorkout(w:WorkoutTemplate){const text=workoutToLiftyText(w);if(navigator.share){try{await navigator.share({title:`Treino LIFTY - ${w.name}`,text});return}catch(err){if(err instanceof DOMException&&err.name==='AbortError')return}}const ok=await copyText(text);alert(ok?'Treino copiado. Agora é só colar e enviar para outra pessoa.':'Não foi possível copiar o treino automaticamente.')}
 async function importText(){if(!sharedText.trim())return alert('Cole o texto do treino LIFTY.');try{const ids=await importLiftyText(sharedText);setSharedText('');setShowTextImport(false);await load();alert(`${ids.length} treino(s) importado(s) com sucesso.`)}catch(err){alert(err instanceof Error?err.message:'Texto de treino inválido ou incompatível.')}}
 return <div className="page"><PageHeader title="Meus Treinos" subtitle="Crie, organize e gerencie seus treinos"/><div className="feature-grid workout-main-actions"><button className="card feature-button" onClick={()=>nav('/treinos/novo')}><Plus/><div><strong>Novo treino</strong><small>Crie um treino híbrido</small></div></button><button className="card feature-button" onClick={()=>nav('/treinos/ia-import')}><Sparkles/><div><strong>IA Treino Import</strong><small>Crie com IA e importe para o LIFTY</small></div></button><button className="card feature-button" onClick={()=>nav('/treinos/prontos')}><BookOpen/><div><strong>Treinos Prontos</strong><small>Biblioteca separada de modelos</small></div></button></div><div className="conventional-import"><button className="secondary compact-import" onClick={()=>setShowTextImport(v=>!v)}><ClipboardPaste size={17}/>Importar treino por texto</button></div>{showTextImport&&<section className="card text-import-card"><div className="section-title-row"><div><h2>Importar treino</h2><small>Cole um ou vários textos LIFTY recebidos de outra pessoa ou gerados por IA.</small></div><button className="icon-btn" onClick={()=>setShowTextImport(false)}><X size={18}/></button></div><textarea rows={12} value={sharedText} onChange={e=>setSharedText(e.target.value)} placeholder="=== LIFTY WORKOUT === ..."/><button className="primary full" onClick={()=>void importText()}><ClipboardPaste size={18}/>Importar treino(s)</button></section>}<section className="stack"><div className="section-strip">Seus treinos</div>{list.map(w=><article className="card compact" key={w.id}><div className="section-title-row"><div><h3>{w.name}</h3><small>{w.blocks.length} bloco(s) • {w.blocks.reduce((a,b)=>a+b.exercises.length,0)} exercícios</small></div><div className="actions"><button className="icon-btn" onClick={()=>nav(`/treinos/editar/${w.id}`)}><Pencil size={17}/></button><button className="icon-btn" onClick={()=>void duplicate(w)}><Copy size={17}/></button><button className="icon-btn" title="Compartilhar treino" onClick={()=>void shareWorkout(w)}><Share2 size={17}/></button><button className="icon-btn" onClick={()=>void saveReady(w)}><BookOpen size={17}/></button><button className="icon-btn danger" onClick={async()=>{if(confirm(`Excluir “${w.name}”? O histórico será preservado.`)){await db.workouts.delete(w.id!);await load()}}}><Trash2 size={17}/></button></div></div><div className="chip-row">{w.blocks.map(b=><span className="chip" key={b.id}>{b.name} • {labels[b.model]}</span>)}</div></article>)}</section></div>}
